"""Pydantic schemas for pipeline data contracts.

Per Rule 4 (VALIDATE LLM OUTPUT):
- All JSON returned by Gemini must be validated against these Pydantic schemas.
- Invalid outputs trigger bounded retries, then deterministic fallback templates.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class IdeaConcept(BaseModel):
    """Structured concept contract generated by the Ideator agent."""
    topic: str = Field(
        ...,
        description="High-engagement, click-worthy video topic title",
        min_length=3
    )
    niche: str = Field(
        default="tech",
        description="Content niche/category (e.g. 'tech', 'finance', 'history', 'science', 'psychology')"
    )
    angle: str = Field(
        ...,
        description="Unique perspective, curiosity gap, or hook angle for the video",
        min_length=5
    )
    target_duration: int = Field(
        default=30,
        description="Target duration of the short-form video in seconds",
        ge=15,
        le=60
    )


class ScriptSegment(BaseModel):
    """An individual scene/beat within a video script."""
    segment_index: int = Field(
        ...,
        description="1-based index indicating the order of the segment in the video",
        ge=1
    )
    narration: str = Field(
        ...,
        description="Spoken voiceover script for this segment (concise, high-impact English)",
        min_length=3
    )
    visual_query: str = Field(
        ...,
        description="Search keywords for stock footage or prompt description for image generation (e.g. 'cinematic close up of futuristic robot')",
        min_length=3
    )
    visual_shots: Optional[List[str]] = Field(
        default=None,
        description="Optional list of 2 to 3 rapid micro-shot visual queries (1.5s to 2.5s each) for fast-paced visual cuts"
    )
    beat: Optional[str] = Field(
        default=None,
        description="Narrative beat role (e.g. 'HOOK', 'TENSION', 'ESCALATION', 'REVELATION', 'LOOP')"
    )
    duration_seconds: float = Field(
        ...,
        description="Estimated duration of this segment in seconds (typically 3 to 10 seconds)",
        ge=1.0
    )


class Script(BaseModel):
    """Complete structured video script contract."""
    topic: str = Field(
        ...,
        description="The primary topic or title of the video",
        min_length=3
    )
    niche: Optional[str] = Field(
        default="general",
        description="Content category (e.g. 'tech', 'finance', 'history', 'psychology', 'general')"
    )
    target_duration: int = Field(
        ...,
        description="Target total duration of the short-form video in seconds (typically 30-60)",
        ge=10,
        le=120
    )
    hook: str = Field(
        ...,
        description="First 3-second hook designed to capture immediate attention and stop the scroll",
        min_length=5
    )
    segments: List[ScriptSegment] = Field(
        ...,
        description="Ordered list of narrative segments forming the body of the script",
        min_length=1
    )
    cta: Optional[str] = Field(
        default=None,
        description="Optional closing call-to-action (e.g. 'Follow for daily tech insights')"
    )
    loop_outro: Optional[str] = Field(
        default=None,
        description="Optional closing sentence designed to flow grammatically into the first word of the hook"
    )

    def full_narration(self) -> str:
        """Returns the complete combined voiceover text."""
        parts = [self.hook]
        for seg in self.segments:
            parts.append(seg.narration)
        if self.loop_outro:
            parts.append(self.loop_outro)
        elif self.cta:
            parts.append(self.cta)
        return " ".join(p.strip() for p in parts if p.strip())

    def total_estimated_duration(self) -> float:
        """Returns the sum of all segment durations."""
        return sum(s.duration_seconds for s in self.segments)
